export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const KART_NOTIFICATION = "KART_NOTIFICATION";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const INCREASE_ITEM ="INCREASE_ITEM";
export const DECREASE_ITEM = "DECREASE_ITEM";